[package]
name = "xos"
version = "0.1.0"
edition = "2021"
description = "Experimental OS Windows Manager"
authors = ["Dyllan McCreary <dyllan@xlate.ai>"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pixels = "0.13.0"
winit = "0.28.6"
winapi = { version = "0.3.9", features = ["winuser"] }
clap = { version = "4.4.10", features = ["derive"] }
cpal = "0.15.2"
tiny_http = "0.12"
js-sys = "0.3.64"
webbrowser = "0.8"
wasm-bindgen = "0.2"
console_error_panic_hook = "0.1"
web-sys = { version = "0.3", features = [
  "CanvasRenderingContext2d",
  "HtmlCanvasElement",
  "ImageData",
  "Document",
  "Window",
  "MouseEvent"
]}


[lib]
name = "xos"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "xos"
path = "src/main.rs"