[package]
name = "xos"
version = "0.1.22"
edition = "2021"
description = "Experimental OS Windows Manager"
authors = ["Dyllan McCreary <dyllan@xlate.ai>"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []  # no features enabled by default
python = ["pyo3", "pyo3/extension-module"]

[dependencies]
pixels = "0.13.0"
winit = "0.28.6"
winapi = { version = "0.3.9", features = ["winuser"] }
clap = { version = "4.4.10", features = ["derive"] }
cpal = "0.15.2"
tiny_http = "0.12"
webbrowser = "0.8"
once_cell = "1.19"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
rand = "0.8"
nokhwa = { version = "0.10.7", features = ["input-native"] }
image = { version = "0.25", features = ["default-formats"] }
pyo3 = { version = "0.21", optional = true, features = ["extension-module"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
web-sys = { version = "0.3", features = [
  "CanvasRenderingContext2d",
  "HtmlCanvasElement",
  "ImageData",
  "Document",
  "Window",
  "MouseEvent",
  "Navigator",
  "MediaDevices",
  "MediaStream",
  "MediaStreamConstraints",
  "HtmlVideoElement",
  "HtmlMediaElement"
] }
console_error_panic_hook = "0.1"

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "xos"
path = "src/main.rs"