platform :ios, '15.1'
use_frameworks! :linkage => :static

# If project doesn't exist, CocoaPods will create it
# But we need at least a basic project structure
project 'xos.xcodeproj'

target 'xos' do
  pod 'Xos', :path => '.'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '5.9'
    end
  end
end

