name: rust crate

on:
  push:
    branches: [main]

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    permissions:
      contents: write # needed for git tagging
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Get current version from Cargo.toml
        id: get-version
        run: |
          version=$(grep '^version =' Cargo.toml | head -n1 | cut -d '"' -f2)
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Check if tag already exists
        id: check-tag
        run: |
          version="v${{ steps.get-version.outputs.version }}"
          if git tag --list | grep -q "$version"; then
            echo "Tag $version already exists. Skipping publish."
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "Tag $version does not exist. Proceeding."
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Publish to crates.io
        if: steps.check-tag.outputs.exists == 'false'
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          cargo publish --no-verify

      - name: Tag commit with version
        if: steps.check-tag.outputs.exists == 'false'
        run: |
          version="v${{ steps.get-version.outputs.version }}"
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag "$version"
          git push origin "$version"
