name: rust crate

on:
  push:
    branches: [main]

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    permissions:
      contents: write # for git tagging
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Get version from Cargo.toml
        id: get-version
        run: |
          version=$(grep '^version =' Cargo.toml | head -n1 | cut -d '"' -f2)
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Check if version exists on crates.io
        id: version-check
        run: |
          crate_name=$(grep '^name =' Cargo.toml | head -n1 | cut -d '"' -f2)
          version="${{ steps.get-version.outputs.version }}"
          echo "Checking if $crate_name@$version exists on crates.io..."
          
          if cargo search "$crate_name" | grep -E "^$crate_name = \"$version\""; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Publish to crates.io
        if: steps.version-check.outputs.exists == 'false'
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish --no-verify

      - name: Log skipped publish
        if: steps.version-check.outputs.exists == 'true'
        run: echo "Version already exists on crates.io. Skipping publish."
